version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27017:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - mongors-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - mongors-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  # nodejs:
  #   depends_on:
  #     - mongo1
  #   container_name: PAW_PI
  #   image: node:14
  #   command: npm run dev
  #   ports:
  #       - "1000:1000"
  #   environment:
  #       NODE_ENV: ${NODEJS_ENV}
  #   volumes:
  #       - ${PWD}:/Users/pitieu/Code/pawpaw
  #   working_dir: /Users/pitieu/Code/pawpaw
    
networks:
  mongors-network:
    driver: bridge
    ipam:
      driver: default
  